-- Future coupon template for shrikantkallurkar (NOT active — do not run unless adding coupons)
-- cd worker && npx wrangler d1 execute mentoria-db --remote --file="../scripts/seed-d1-coupons.sql"
--
-- INSERT OR REPLACE INTO coupons (code, discount_type, value, min_amount, max_discount, active, expires_at, project_id, id, discount_value)
-- VALUES
--   ('YOURCODE', 'percentage', 10, 0, NULL, 1, NULL, 'shrikantkallurkar', 'shrikantkallurkar-YOURCODE', 10);
